export const ADMINISTRATED = "ADMINISTRATED",
    NOTADMINISTRATED = "NOTADMINISTRATED",
    TOBEADMINISTRATED = "TOBEADMINISTRATED",
    MG = "MG", ML = "ML",
    CAP = "CAPSULES", TAB = "TABLETS",
    TBSP = "TABLESPOON", TSP = "TEASPOON",
    QD = "ONCE A DAY", BID = "TWICE A DAY",
    TID = "THRICE A DAY", QID = "FOUR TIMES A DAY",
    QOD = "ON ALTERNATE DAYS",
    SYMBOLSHEXCODE = {
      ADMINISTRATED: 0X2705,
      TOBEADMINISTRATED: 0X23F0,
      NOTADMINISTRATED: 0X26A0
    },
    STARTOFWEEK = 1
;
